version: '3.9'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/grocery
    depends_on:
      - mongo
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
